# Generated by Django 4.2.7 on 2023-12-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='details',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
