# Generated by Django 4.2.7 on 2023-12-03 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Details',
        ),
    ]
