# Generated by Django 4.2.7 on 2023-12-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
