# Generated by Django 4.2.7 on 2023-12-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
