# Generated by Django 4.2.7 on 2023-12-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='requirement1',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirement2',
        ),
        migrations.RemoveField(
            model_name='job',
            name='requirement3',
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
    ]
