# Generated by Django 4.2.7 on 2023-12-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reject', 'Reject'), ('Open', 'Open'), ('Closed', 'Closed')], default='Pending', max_length=10),
        ),
    ]
