# Generated by Django 4.2.7 on 2023-12-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_rename_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='company',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='details',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
