# Generated by Django 4.2.7 on 2023-12-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_applicant_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='rejection_reason',
        ),
    ]
