# Generated by Django 4.2.7 on 2023-12-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_remove_applicant_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
