# Generated by Django 4.2.7 on 2023-12-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_job_details_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=100)),
                ('resume', models.FileField(upload_to='resume/')),
                ('job', models.CharField(default='', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
