# Generated by Django 4.2.7 on 2023-12-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_applicant_remove_job_company_job_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(upload_to='employer/applicants/resume/'),
        ),
    ]
