# Generated by Django 4.2.7 on 2023-12-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_alter_applicant_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='company',
            field=models.CharField(default='', max_length=50),
        ),
    ]
