# Generated by Django 4.2.7 on 2023-12-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_reason', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(max_length=100)),
                ('training_institution', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('credits_earned', models.PositiveIntegerField()),
                ('employee_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CareerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('started', models.DateField()),
                ('ended', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('college_or_university', models.CharField(max_length=255)),
                ('year_graduated', models.PositiveIntegerField()),
                ('honors_or_awards', models.TextField(blank=True, null=True)),
                ('employee_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='user', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(default='email@email.com', max_length=255, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('region_of_origin', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('location_of_residence', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(default='password', max_length=255)),
                ('profile_picture_path', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GraduateTracer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('year_graduated', models.IntegerField(choices=[(1950, '1950'), (1951, '1951'), (1952, '1952'), (1953, '1953'), (1954, '1954'), (1955, '1955'), (1956, '1956'), (1957, '1957'), (1958, '1958'), (1959, '1959'), (1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')])),
                ('address', models.CharField(max_length=255)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=11)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('education_attained', models.CharField(choices=[('Certificate in Two Year Course', 'Certificate in Two Year Course'), ('College graduate', 'College graduate'), ('With Units in Masters Degree', 'With Units in Masters Degree'), ('Masters Degree Holder', 'Masters Degree Holder'), ('With Units in Doctoral Degree', 'With Units in Doctoral Degree'), ('Doctoral Degree Holder', 'Doctoral Degree Holder')], max_length=50)),
                ('scholarship_recipient', models.CharField(choices=[('Yes, I am recipient of Government scholarship program', 'Yes, I am recipient of Government scholarship program'), ('Yes, I am recipient of private scholarship program', 'Yes, I am recipient of private scholarship program'), ('No, I am not recipient of any scholarship program', 'No, I am not recipient of any scholarship program')], max_length=100)),
                ('presently_employed', models.CharField(choices=[('Yes with employer', 'Yes with employer'), ('Yes self-employed', 'Yes self-employed'), ('No', 'No')], max_length=20)),
                ('organization_or_employer', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('Public/Government', 'Public/Government'), ('NGO', 'NGO'), ('Non-profit', 'Non-profit'), ('Private Owned', 'Private Owned')], max_length=20)),
                ('employment_status', models.CharField(choices=[('Regular/Permanent', 'Regular/Permanent'), ('Temporary', 'Temporary'), ('Casual', 'Casual'), ('Contractual', 'Contractual'), ('Self-employed', 'Self-employed')], max_length=20)),
                ('work_location', models.CharField(choices=[('Local', 'Local'), ('Abroad', 'Abroad')], max_length=10)),
                ('current_occupation', models.CharField(max_length=255)),
                ('years_in_company', models.CharField(max_length=3)),
                ('major_line_of_business', models.CharField(choices=[('BPO', 'BPO'), ('Trade/Industry', 'Trade/Industry'), ('Legal', 'Legal'), ('Telecom/Communications', 'Telecom/Communications'), ('IT/Computer/Software', 'IT/Computer/Software'), ('Banking and Finance', 'Banking and Finance'), ('Insurance', 'Insurance'), ('Services', 'Services'), ('Government', 'Government'), ('Academic', 'Academic'), ('Manufacturing', 'Manufacturing'), ('Other', 'Other')], max_length=50)),
                ('reason_to_stay', models.CharField(max_length=255)),
                ('gross_monthly_rate', models.CharField(choices=[('Below P 10,000', 'Below P 10,000'), ('P 10,000 to P 20,000', 'P 10,000 to P 20,000'), ('P 21,000 to P 30,000', 'P 21,000 to P 30,000'), ('P 31,000 to P 40,000', 'P 31,000 to P 40,000'), ('P 41,000 to P 50,000', 'P 41,000 to P 50,000'), ('P 51,000 to P 60,000', 'P 51,000 to P 60,000'), ('P 61,000 to P 70,000', 'P 61,000 to P 70,000'), ('Above P 71,000', 'Above P 71,000')], max_length=20)),
                ('award', models.CharField(max_length=255)),
                ('key_position', models.CharField(max_length=255)),
                ('course_related_to_job', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('first_job_found_duration', models.CharField(choices=[('Less than a month', 'Less than a month'), ('1-3 months', '1-3 months'), ('3-6 months', '3-6 months'), ('6-12 months', '6-12 months'), ('Above 1 year', 'Above 1 year'), ('Above 3 years', 'Above 3 years')], max_length=20)),
                ('first_job_present', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('first_job_stay_duration', models.CharField(choices=[('Less than a month', 'Less than a month'), ('1-3 months', '1-3 months'), ('3-6 months', '3-6 months'), ('6-12 months', '6-12 months'), ('Above 1 year', 'Above 1 year'), ('Still working on the first job', 'Still working on the first job')], max_length=50)),
                ('known_first_job_through', models.CharField(choices=[('Response to advertisement', 'Response to advertisement'), ("Arranged by school's job placement offer", "Arranged by school's job placement offer"), ('Walk-in applicant', 'Walk-in applicant'), ('Family business', 'Family business'), ('Recommended by someone', 'Recommended by someone'), ('Info from friends', 'Info from friends'), ('Other', 'Other')], max_length=50)),
                ('first_job_level_position', models.CharField(choices=[('Rank or clerical', 'Rank or clerical'), ('Professional, technical, or supervisory', 'Professional, technical, or supervisory'), ('Managerial or executive', 'Managerial or executive'), ('Self-employed', 'Self-employed')], max_length=50)),
                ('gross_monthly_earning_first_job', models.CharField(choices=[('Below P 10,000', 'Below P 10,000'), ('P 10,000 to P 20,000', 'P 10,000 to P 20,000'), ('P 21,000 to P 30,000', 'P 21,000 to P 30,000'), ('P 31,000 to P 40,000', 'P 31,000 to P 40,000'), ('P 41,000 to P 50,000', 'P 41,000 to P 50,000'), ('P 51,000 to P 60,000', 'P 51,000 to P 60,000'), ('P 61,000 to P 70,000', 'P 61,000 to P 70,000'), ('Above P 71,000', 'Above P 71,000')], max_length=20)),
                ('curriculum_related_to_first_job', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('communication_skills', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('human_relations_skills', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('entrepreneurial_skills', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('information_technology_skills', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('problem_solving_skills', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('critical_thinking_skills', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
            ],
        ),
        migrations.CreateModel(
            name='MyJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=255)),
                ('job', models.CharField(default='job', max_length=255)),
                ('company', models.CharField(default='company', max_length=255)),
                ('status', models.CharField(default='status', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(max_length=255)),
                ('exam_date', models.DateField()),
                ('exam_rating', models.FloatField()),
                ('employee_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='email@email.com', max_length=255, unique=True)),
                ('password', models.CharField(default='password', max_length=255)),
            ],
        ),
    ]
