# Generated by Django 4.2.7 on 2023-12-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='address', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='first_name', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='last_name', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='phone_number', max_length=255),
        ),
    ]
