# Generated by Django 4.2.7 on 2023-12-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('college_or_university', models.CharField(max_length=255)),
                ('year_graduated', models.PositiveIntegerField()),
                ('honors_or_awards', models.TextField(blank=True, null=True)),
                ('employee_id', models.CharField(max_length=20)),
            ],
        ),
    ]
