# Generated by Django 4.2.7 on 2023-12-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_educationalbackground'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=255)),
                ('started', models.DateField()),
                ('ended', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee_id', models.CharField(max_length=20)),
            ],
        ),
    ]
