# Generated by Django 4.2.7 on 2023-12-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_careerhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_title', models.CharField(max_length=100)),
                ('training_institution', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('credits_earned', models.PositiveIntegerField()),
                ('employee_id', models.CharField(max_length=20)),
            ],
        ),
    ]
