# Generated by Django 4.2.7 on 2023-12-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_advancestudies'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_reason', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=20)),
            ],
        ),
    ]
