# Generated by Django 4.2.7 on 2023-12-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(max_length=255)),
                ('exam_date', models.DateField()),
                ('exam_rating', models.FloatField()),
                ('employee_id', models.CharField(max_length=20)),
            ],
        ),
    ]
